version: "3"

services:
  homarr-iframes:
    container_name: homarr-iframes
    image: ghcr.io/diogovalentte/homarr-iframes:latest
    user: 1000:1000
    environment:
      - TZ=${TZ:-UTC} # uses UTC if not specified
      - PORT=${PORT:-8080} # uses port 8080 if not specified

      - LINKWARDEN_ADDRESS=${LINKWARDEN_ADDRESS:-}
      - INTERNAL_LINKWARDEN_ADDRESS=${INTERNAL_LINKWARDEN_ADDRESS:-}
      - LINKWARDEN_TOKEN=${LINKWARDEN_TOKEN:-}

      - VIKUNJA_ADDRESS=${VIKUNJA_ADDRESS:-}
      - INTERNAL_VIKUNJA_ADDRESS=${INTERNAL_VIKUNJA_ADDRESS:-}
      - VIKUNJA_TOKEN=${VIKUNJA_TOKEN:-}

      - OVERSEERR_ADDRESS=${OVERSEERR_ADDRESS:-}
      - INTERNAL_OVERSEERR_ADDRESS=${INTERNAL_OVERSEERR_ADDRESS:-}
      - OVERSEERR_API_URL=${OVERSEERR_API_URL:-}

      - JELLYSEERR_ADDRESS=${JELLYSEERR_ADDRESS:-}
      - INTERNAL_JELLYSEERR_ADDRESS=${INTERNAL_JELLYSEERR_ADDRESS:-}
      - JELLYSEERR_API_URL=${JELLYSEERR_API_URL:-}

      - SONARR_ADDRESS=${SONARR_ADDRESS:-}
      - INTERNAL_SONARR_ADDRESS=${INTERNAL_SONARR_ADDRESS:-}
      - SONARR_API_KEY=${SONARR_API_KEY:-}

      - RADARR_ADDRESS=${RADARR_ADDRESS:-}
      - INTERNAL_RADARR_ADDRESS=${INTERNAL_RADARR_ADDRESS:-}
      - RADARR_API_KEY=${RADARR_API_KEY:-}

      - UPTIMEKUMA_ADDRESS=${UPTIMEKUMA_ADDRESS:-}

      - NETDATA_ADDRESS=${NETDATA_ADDRESS:-}
      - INTERNAL_NETDATA_ADDRESS=${INTERNAL_NETDATA_ADDRESS:-}
      - NETDATA_TOKEN=${NETDATA_TOKEN:-}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8080:8080
    restart: on-failure
