version: "3"

services:
  homarr-iframes:
    container_name: homarr-iframes
    image: ghcr.io/diogovalentte/homarr-iframes:latest
    user: 1000:1000
    environment:
      - TZ=${TZ:-UTC} # uses UTC if not specified
      - PORT=${PORT:-8080} # uses port 8080 if not specified

      - LINKWARDEN_ADDRESS=${LINKWARDEN_ADDRESS:-}
      - INTERNAL_LINKWARDEN_ADDRESS=${INTERNAL_LINKWARDEN_ADDRESS:-}
      - LINKWARDEN_TOKEN=${LINKWARDEN_TOKEN:-}
      - LINKWARDEN_BACKGROUND_IMG_URL=${LINKWARDEN_BACKGROUND_IMG_URL:-}

      - VIKUNJA_ADDRESS=${VIKUNJA_ADDRESS:-}
      - INTERNAL_VIKUNJA_ADDRESS=${INTERNAL_VIKUNJA_ADDRESS:-}
      - VIKUNJA_TOKEN=${VIKUNJA_TOKEN:-}
      - VIKUNJA_BACKGROUND_IMG_URL=${VIKUNJA_BACKGROUND_IMG_URL:-}

      - OVERSEERR_ADDRESS=${OVERSEERR_ADDRESS:-}
      - INTERNAL_OVERSEERR_ADDRESS=${INTERNAL_OVERSEERR_ADDRESS:-}
      - OVERSEERR_API_KEY=${OVERSEERR_API_KEY:-}

      - JELLYSEERR_ADDRESS=${JELLYSEERR_ADDRESS:-}
      - INTERNAL_JELLYSEERR_ADDRESS=${INTERNAL_JELLYSEERR_ADDRESS:-}
      - JELLYSEERR_API_KEY=${JELLYSEERR_API_KEY:-}

      - SONARR_ADDRESS=${SONARR_ADDRESS:-}
      - INTERNAL_SONARR_ADDRESS=${INTERNAL_SONARR_ADDRESS:-}
      - SONARR_API_KEY=${SONARR_API_KEY:-}

      - RADARR_ADDRESS=${RADARR_ADDRESS:-}
      - INTERNAL_RADARR_ADDRESS=${INTERNAL_RADARR_ADDRESS:-}
      - RADARR_API_KEY=${RADARR_API_KEY:-}

      - UPTIMEKUMA_ADDRESS=${UPTIMEKUMA_ADDRESS:-}
      - INTERNAL_UPTIMEKUMA_ADDRESS=${INTERNAL_UPTIMEKUMA_ADDRESS:-}

      - NETDATA_ADDRESS=${NETDATA_ADDRESS:-}
      - INTERNAL_NETDATA_ADDRESS=${INTERNAL_NETDATA_ADDRESS:-}
      - NETDATA_TOKEN=${NETDATA_TOKEN:-}

      - SPEEDTEST_TRACKER_ADDRESS=${SPEEDTEST_TRACKER_ADDRESS:-}
      - INTERNAL_SPEEDTEST_TRACKER_ADDRESS=${INTERNAL_SPEEDTEST_TRACKER_ADDRESS:-}
      - SPEEDTEST_TRACKER_TOKEN=${SPEEDTEST_TRACKER_TOKEN:-}

      - PIHOLE_ADDRESS=${PIHOLE_ADDRESS:-}
      - INTERNAL_PIHOLE_ADDRESS=${INTERNAL_PIHOLE_ADDRESS:-}
      - PIHOLE_TOKEN=${PIHOLE_TOKEN:-} # pihole <v6.0
      - PIHOLE_PASSWORD=${PIHOLE_PASSWORD:-} # pihole >=v6.0

      - KAVITA_ADDRESS=${KAVITA_ADDRESS:-}
      - INTERNAL_KAVITA_ADDRESS=${INTERNAL_KAVITA_ADDRESS:-}
      - KAVITA_USERNAME=${KAVITA_USERNAME:-}
      - KAVITA_PASSWORD=${KAVITA_PASSWORD:-}

      - KAIZOKU_ADDRESS=${KAIZOKU_ADDRESS:-}
      - INTERNAL_KAIZOKU_ADDRESS=${INTERNAL_KAIZOKU_ADDRESS:-}

      - CHANGEDETECTIONIO_ADDRESS=${CHANGEDETECTIONIO_ADDRESS:-}
      - INTERNAL_CHANGEDETECTIONIO_ADDRESS=${INTERNAL_CHANGEDETECTIONIO_ADDRESS:-}
      - CHANGEDETECTIONIO_API_KEY=${CHANGEDETECTIONIO_API_KEY:-}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8080:8080
    restart: on-failure
