version: "3"

services:
  homarr-iframes:
    container_name: homarr-iframes
    image: ghcr.io/diogovalentte/homarr-iframes:latest
    user: 1000:1000
    environment:
      - TZ=${TZ:-UTC} # uses UTC if not specified
      - PORT=${PORT:-8080} # uses port 8080 if not specified

      - LINKWARDEN_ADDRESS=${LINKWARDEN_ADDRESS:-}
      - LINKWARDEN_TOKEN=${LINKWARDEN_TOKEN:-}

      - VIKUNJA_ADDRESS=${VIKUNJA_ADDRESS:-}
      - VIKUNJA_TOKEN=${VIKUNJA_TOKEN:-}

      - OVERSEERR_ADDRESS=${OVERSEERR_ADDRESS:-}
      - OVERSEERR_TOKEN=${OVERSEERR_TOKEN:-}

      - UPTIMEKUMA_ADDRESS=${UPTIMEKUMA_ADDRESS:-}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8080:8080
    restart: on-failure
